version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    expose:
    - "5432"
    command: postgres --fsync=off --synchronous_commit=off --full_page_writes=off
    
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  db:
    driver: local